image: jekyll/builder

before_script:
  - echo "[$CI_JOB_NAME] Job for $CI_PROJECT_NAME started by $GITLAB_USER_NAME"

stages:
  - install
  - compile
  - deploy

run-install:
  stage: install
  tags:
    - docker-runner
  script:
    - apk update && apk add -u yarn libpng-dev libjpeg-turbo-dev libjpeg-turbo-utils zip
    - yarn
  cache:
    key: yarn
    paths:
      - node_modules
  only:
    - development
    - master

compile-project:
  stage: compile
  tags:
    - docker-runner
  script:
    - echo "compile assets and jekyll"
    - apk update && apk add -u zip
    - echo "" >> _config.yml
    - 'echo "baseurl: /$CI_PROJECT_NAME" >> _config.yml'
    - 'echo "url: http://html.netcore.lv" >> _config.yml'
    - mkdir _site && chmod 0777 _site
    - yarn gulp prod
  cache:
    key: yarn
    paths:
      - node_modules
  artifacts:
    expire_in: 7d
    paths:
      - _site
  only:
    - development
    - master
  when: on_success

deploy-project:
  stage: deploy
  tags:
    - shell-runner
  before_script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - ssh-keyscan spark.rackblaze.net >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add /srv/gitlab/frontend-deploy-priv.key
  script:
    - zip -qr _site.zip _site
    - mv _site.zip _site
    #- ssh -p 22 htmlnetcore@spark.rackblaze.net '(whoami)'
    - rsync -crz --del $CI_PROJECT_DIR/_site/ htmlnetcore@spark.rackblaze.net:/home/htmlnetcore/public_html/$CI_PROJECT_NAME/
  only:
    - development
    - master
  when: on_success
